plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
Layout/LineLength:
  Max: 150
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'shared_examples', 'it', 'before', 'namespace']
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
