AllCops:     
  NewCops: enable
  Exclude:
    - 'vendor/'
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'shared_examples', 'it', 'before', 'namespace']
