AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
Layout/LineLength:
  Max: 150
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'shared_examples', 'it', 'before', 'namespace']
