language: ruby
cache: bundler
rvm:
- 2.7.0
before_install: gem install bundler -v 2.1.4
script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure: H5ZtTBqEMULfn1ffM8YA5EQULQzrUa61fGQ5dqWrNNHFSBdqSHVqVl9HUJ2BjVpM8VNuQ0o2m4iB/MZ1VcFNGjxedXmfrDH5pyhcvAWkmtbL80R9GFmnLIxMpvxR1P/P5YXEzlhoCkwsxt2cWKcLclQ4BCrzSbzzNbW0B5bct344qOywOvFMVScl4q6UyHEwC3Ev9MlKuHo/mIFAo2TLm6VkwsCl6hL4GmKYa1DJNuAYh5pcWtdlouUOyLXk4PYYR6Kqr+bc93XXVDc/rwoxpjl6NLp4shz09amugcjLKzfdhhVwlOBINTdMq7frsfaLK6yAKv2KyfYUNslL4+Yt9yecGlNJK3zID6Q4VEoza5s1WIEWauHRkym/l10ien4Tog1KYJMP5ZuVTB6n87tbWZNxlxm/q/e1YUvA8stkrQccP+p/icALs4jda4fKxCx/hsDzGuQlQNvH0Ob0XhJUjtbUGmEgk7vErpta4vWzK2Z+NTA1X1o53TBiDybY5hA7N7Q9PAz2FOp0CgrxKgrjDJTUJ1BVZIgYW/HNrLEM0B/snL7OKmfUNgAbnjxT0Nt8aen+g+Cy/3BtBLbxPxslPfKZDMN7X5zECLH6L3gPd5QmZyfIwKMmteqCM8IITuNACJVcFYOdHC7iSQbzdUsd+8mJLwbLEByWRzHRLO0njV0=
  gem: guard-busted
  on:
    tags: true
    repo: pjezusek/guard-busted
  skip_cleanup: 'true'
