language: ruby
cache: bundler
rvm:
- 2.7.0
before_install: gem install bundler -v 2.1.4
script: bundle exec rake spec
deploy:
  provider: rubygems
  api_key:
    secure: ojP3qWnYJs22jKlMRpE1Y20xGgRYCRIo2vg7w7cyo8QKKOF8UiY4P5sI+mb2BEvqeOmHzRcaQkck9jXbXsD5PP4zVI0bwO1JmcVvdHsOeczNqdkVUaGEw716Mn/7sRIOSlhRK6qGcvVk7DrXTBtR+vaS0M8oDcC8vWE1FfJ/CYZh2DED32rpb6rBB9sjWWuwfRdv1MkKLV7yx6MIzZBjDwuYXq0EqJEhxEC8HlSBe07EfVGjrtWnz0RI23R2oY2Hh7VtO6BAPBUqkybZqTF0OTrBoLIFbBgY3rHPqB1gKmU1QHdb72b4TRIEFcG2VBBnW5i9TYEUjtE3I1VifRMb1AnaMiAjzJgiyvItPz+/8ayFcfj/x1r2BXSEynH2IQOAxQVa0wuzy1+iClZv10+zw73iScwnwMemDQqnnIs6pE9Ch/x/ea4vM2UyApKJnpDCkZpDTiq2CD4CP/yhjPgWyaAweAwjvKcid6tGEuec0YEKZViqmQ0JFWIQ4k04Xxw7vj9cRROCLNxZ2/A68frJOiCXljvY18VUfj9CwfM3G8QqPbyGE3kPxbn+DpfneIHXW7amfSArZ3w+APUF1rIdi+ab54bTpKFYvh3/K2eLrLJK7N26wuvhQEJLKTUT6txR0I0maUFAQVutPXXacNyFu0Drd1VHx7B7ifq/Pq83bno=
  gem: guard-busted
  on:
    tags: true
    repo: pjezusek/guard-busted
  skip_cleanup: 'true'
