# frozen_string_literal: true

guard :busted do
  watch(%r{^spec/.*\.lua$})
  watch(%r{(?!src)^(.*)\.lua$}) { |m| "spec/#{m[1]}_spec.lua" }
  watch(%r{^src/(.*)\.lua$}) { |m| "spec/#{m[1]}_spec.lua" }
end
