name: RSpec

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.3']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        cache-version: 1
    - name: Install dependencies
      run: bundle install --without development
    - name: Run tests
      run: bundle exec rake
    - name: Send test coverage report
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/coverage.xml
